### ISSUE TITLE
Some players only one cobblestone generator works

### ISSUE THREAD

**Issue by andris155** [Sfiguz7/ExtraTools#1]
## Description (Required)

Some players only one cobblestone generator works

## Steps to reproduce the Issue (Required)

https://www.youtube.com/watch?v=-Gb2mcLPBXk

## Expected behavior (Required)

Works all placed cobblestone generator.

## Environment (Required)

 - Minecraft Version: 1.15.2
 - CS-CoreLib Version: vDEV - 83 (git 8081bb4f)
 - Slimefun Version: vDEV - 477 (git 156683f3)
 - Plugin Version: vDEV - 7 (git 9e953653)

**Comment by Alessio-Colombo** [comment]
I could not reproduce the bug, as shown [here](https://youtu.be/pQezjZh7dBk) placing two generators does not seem to be an issue. Could you try using a Multimeter (Technical Gadgets) to check if they both have energy? It's likely to just be a power issue.
Leaving this open for a reply and maybe more testing if further info on what could the cause be is provided.

**Comment by poma123** [comment]
Both have energy, but one does not work.

**Comment by Alessio-Colombo** [comment]
Found what is likely the issue, will push a new commit very soon which will fix it. Please update to the new build ASAP!
If you wouldn't mind confirming it works for you via Discord (Sfiguz7#7063) I'd appreciate it :)

**Comment by andris155** [comment]
Thanks!

**Comment by weyaj** [comment]
nem adtam ra engedelyt h torold a kommentem gecukam
angoltudas 00000000
