### ISSUE TITLE
Cobblestone Generator is Disappearing when placed

### ISSUE THREAD

**Issue by Ac3ofSpad3** [Sfiguz7/ExtraTools#10]
## Description (Required)
Cobblestone generators are disappearing after a few seconds of being placed. The stacktrace makes a comment about only adding positive energy, but it doesn't matter how much power you feed it with, the generators still just disappear.

## Expected behavior (Required)
Cobblestone generator should start producing cobblestone and it's setup to a cargo circuit that sends it off to an automatic grind stone.

## Server Log / Error Report
https://pastebin.com/J6g64Xbv

## Environment (Required)

 - Minecraft Version: v1.16.2-R0.1-SNAPSHOT
 - CS-CoreLib Version: v1.6.3
 - Slimefun Version: vDEV - 669 (git 00e71904)
 - Plugin Version: ExtraTools vDEV - 19 (git c045101c)

**Comment by Alessio-Colombo** [comment]
Update to DEV - 20, it should fix the issue. Please confirm it it does so I can close this!

**Comment by Ac3ofSpad3** [comment]
The update did fix the issue.
