### ISSUE TITLE
Hammer not pulvurizing blocks.

### ISSUE THREAD

**Issue by Ganouit** [Sfiguz7/ExtraTools#12]
## Description (Required)

The hammer is supposed to make the Cobblestone/Stone into gravel as the lore says, it pulvurizes blocks.
I have also tested it with the other blocks and it does not pulvurize the blocks into the wanted resources.

## Steps to reproduce the Issue (Required)

https://youtu.be/Vpqo7J6tGOo

## Expected behavior (Required)

For the Cobblestone/Stone to turn into gravel.

## Server Log / Error Report

There are no errors in the console.

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version: 
![image](https://user-images.githubusercontent.com/63960101/97445132-e50b9700-1967-11eb-9c00-638b083d0111.png)

**Comment by Alessio-Colombo** [comment]
Should be fixed in DEV 22 whenever it comes out, forgot to mention this in the commit so it didn't auto close
