### ISSUE TITLE
java.lang.NoSuchFieldError: ACCESS_INVENTORIES error

### ISSUE THREAD

**Issue by andris155** [Sfiguz7/ExtraTools#14]
## Description (Required)

ExtraTools not works perfectly and writes this error on console.

## Steps to reproduce the Issue (Required)

1. Place Cobblestone generator
2. Right click to the Cobblestone generator

## Expected behavior (Required)

ExtraTools works perfectly and no writes this error on console.

## Server Log / Error Report

https://pastebin.com/80fJAzLN

## Environment (Required)

Yatopia git-Yatopia-ver/1.16.5-21 (MC: 1.16.5)
Slimefun DEV - 812 (git 47743b63)
Metrics-Module #21
Java 11

Installed Addons: (11)
  DyedBackpacks vDEV - 13 (git 964b2d55)
  RestrictedCreative v2.4.6
  ExtraTools vDEV - 23 (git 9299a65c)
  PomaExpansion vDEV - 13 (git 78eb8cc5)
  SFCalc vDEV - 15 (git 6586cb3f)
  LiteXpansion vDEV - 124 (git 0e449831)
  SlimefunFix v1.1-SNAPSHOT
  EcoPower vDEV - 3 (git 18ba903d)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 31 (git 6fa9afbd)
  FluffyMachines vDEV - 64 (git 582f5de7)

**Comment by amarcais53** [comment]
fixed on #15
