### ISSUE TITLE
Error opening the Cobblestone Generator interface

### ISSUE THREAD

**Issue by Zireaphus** [Sfiguz7/ExtraTools#16]
## Description (Required)

When you try to open the Cobblestone Generator interface, an error appears, moreover it is not even possible to open it. However, all other Extratools electrical machines are working correctly.

## Steps to reproduce the Issue (Required)

1 - Place a Cobblestone Generator on the floor.
2 - Try to open his interface.
3 - Look on the console.

## Expected behavior (Required)

Click and open the machine interface correctly without any error appearing on the console.

## Server Log / Error Report

https://pastebin.com/SweLSFFv

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version:
 - Slimefun Version: 915
 - Plugin Version: 26

**Comment by winnipeg21** [comment]
Same issue
https://pastebin.com/VKPEEVNf
