### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Intybyte** [Sfiguz7/ExtraTools#17]
Great plugin, but the hammer at mid game isnt enought to get a lot of gravel, can you add something like an explosive hammer? It works like the explosive pickaxe but gives gravel instead

**Comment by Alessio-Colombo** [comment]
The idea behind not adding one was that the Hammer should help you early game but once you have a cobblestone generator of any sort you can use either the Ore Grinder or the Pulverizer to deal with large amount of materials at a time, without effort; I can add an Explosive Hammer if people seem to like the idea though.
If you could move the suggestion to https://discord.gg/6Vc4A3Zq6r and people upvote it I will make sure to add one :)

In the meantime I will close this just so it's clear it is not an issue, I will keep the suggestion in mind even if it doesn't get too many upvotes though as it should be easy to add so if I get some time I may just throw it in. Thank you for the suggestion!
