### ISSUE TITLE
Electric Composter (II) missing the (II) in its GUI

### ISSUE THREAD

**Issue by marvjosh1** [Sfiguz7/ExtraTools#18]
## Description (Required)
The Electric Composter (II) does not show its level in the gui, in comparison to regular other machines

## Steps to reproduce the Issue (Required)
https://www.youtube.com/watch?v=6r8MhgxJUxg

## Expected behavior (Required)
For the (II) to be shown

## Server Log / Error Report
n/a

## Environment (Required)
https://i.imgur.com/4xJlLfZ.png
https://i.imgur.com/SzCzFfh.png

**Comment by Alessio-Colombo** [comment]
To be precise, this is not fixed on your end since you use a modified version. It is although fixed in the official version
