### ISSUE TITLE
Vaporizer remove the bucket

### ISSUE THREAD

**Issue by andris155** [Sfiguz7/ExtraTools#3]
## Description (Required)

Vaporizer remove the bucket.

## Steps to reproduce the Issue (Required)

1. Place water or lava bucket to the Vaporizer.
2. The Vaporizer removed bucket when progress is done.

## Expected behavior (Required)

The Vaporizer no remove remove the bucket.
Stay the empty bucket.

## Environment (Required)

 - Minecraft Version: 1.15.2
 - CS-CoreLib Version: vDEV - 85 (git 4a7fce52)
 - Slimefun Version: vDEV - 493 (git 4cc6a02)
 - Plugin Version: vDEV - 10 (git afacb57b)

**Comment by Alessio-Colombo** [comment]
To be completely fair my initial idea actually was to consume the bucket so this is intended. After thinking about it though I agree it makes more sense for the bucket to survive so I’ll push a new build changing the output
