### ISSUE TITLE
Cobblestone generator lost when place multiple items Enchanced Crafting Table

### ISSUE THREAD

**Issue by andris155** [Sfiguz7/ExtraTools#5]
## Description (Required)

Cobblestone generator lost when place multiple items Enchanced Crafting Table

## Steps to reproduce the Issue (Required)

https://www.youtube.com/watch?v=hb2oeFTT_yY

## Expected behavior (Required)

Cobblestone generator no lost when place multiple items Enchanced Crafting Table.

## Environment (Required)

 - Minecraft Version: 1.16.1
 - CS-CoreLib Version: 88 (git 6a39a9e7)
 - Slimefun Version: 584 (git 9af90830)
 - Plugin Version: 12 (git 0b915279)

**Comment by Alessio-Colombo** [comment]
This is actually an issue from Slimefun itself, not ExtraTools. No need to worry about creating another issue on the other bug tracker though, I will tomorrow and reference this. Thank you for the report!

**Comment by Alessio-Colombo** [comment]
Was solved 5 hours ago so I'll close and mark resolved :)

**Comment by andris155** [comment]
Thanks!
