### ISSUE TITLE
Cobblestone generator Error 

### ISSUE THREAD

**Issue by Bwe942** [Sfiguz7/ExtraTools#8]
Yesterday I was playing everything was working and today I came across it
https://pastebin.com/AieHwD7i
![Screenshot_3](https://user-images.githubusercontent.com/71046264/92662895-3c7d7700-f2d6-11ea-8151-c221589c3729.png)
![Screenshot_4](https://user-images.githubusercontent.com/71046264/92662897-3daea400-f2d6-11ea-920e-7342a4acd9a9.png)

**Comment by Alessio-Colombo** [comment]
Could you send the report too? In /plugins/Slimefun/error-reports/ folder, as said in the stacktrace

**Comment by Bwe942** [comment]
> Could you send the report too? In /plugins/Slimefun/error-reports/ folder, as said in the stacktrace

https://pastebin.com/AieHwD7i
